version: '3.1'

services:
  springboot:
    image: paramveer1974/gagneza-group:BUILD_NUMBER
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - flipkartnetwork  
   

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - param-vol:/data/db
    restart: always
    networks:
    - flipkartnetwork
    
volumes:
  param-vol:
    external: true
    
networks:
  flipkartnetwork:
    external: true
